### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by DariusIII** [NtimYeboah/laravel-database-trigger#4]
- Package Version: 1.0.0
- PHP Version: 7.2
- Database Driver & Version: Mariadb 10.3

### Description:
As Laravel 5.8 is out, could we have a compatible release?

**Comment by robinhoo1973** [comment]
up

**Comment by the907** [comment]
Up

**Comment by DariusIII** [comment]
While we wait i have forked and updated the code:

https://github.com/DariusIII/laravel-database-trigger

**Comment by DariusIII** [comment]
Package is obviously not maintained anymore.
